# frozen_string_literal: true

module FunHtml
  # HTML attributes autogenerated, do not edit
  module AttributeDefinitions
    sig { params(suffix: String, value: T::Boolean).void }
    def data(suffix, value); end
  end
end
