# frozen_string_literal: true
# typed: false

require 'json'
require 'sorbet-runtime'

module Html
  # generates the HTML node definitions
  module Generator
    def self.call
      source = File.read 'node_modules/@webref/elements/html.json'
      nodes = JSON.parse(source)['elements'].map do |el|
        <<~SRC

          def #{el['name']}(attributes = nil, &elements)
            write('<#{el['name']}', '</#{el['name']}>', attributes, &elements)
          end
        SRC
      end

      source =
        <<~SRC
          module Html
            # HTML nodes autogenerated, do not edit
            module NodeDefinitions
              #{nodes.join("\n\n")}
            end
          end
        SRC

      File.write 'lib/html/node_definitions.rb', source
    end
  end
end
